### ISSUE TITLE
About the coding standard

### ISSUE THREAD

**Issue by cpyberry** [onuratakan/Decentra-Network#10]
Hello, I am cpyberry.
If you happen to have a free moment, I'd be very glad if you could give me your opinion.

What the coding standard does this repository have?

**Comment by cpyberry** [comment]
An example of a coding convention is PEP8

**Comment by onuratakan** [comment]
To be honest, I didn't concentrate on a coding standard. However, the codes are mostly similar to PEP8.

I will change the code to PEP8 format soon.

**Comment by onuratakan** [comment]
I made a commit for PEP8

https://github.com/onuratakan/Decentra-Network/commit/8776ee03f0734375eb810858b36b0be90a81eb31
